# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration) 

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: 'Publish Database'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: publish
    projects: 'src/Database/LoLPredict.Database'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/Database'
    zipAfterPublish: false

- task: DotNetCoreCLI@2
  displayName: 'Publish Web'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: publish
    projects: 'src/Web/LoLPredict.Web'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/Web'
    zipAfterPublish: True

- task: DotNetCoreCLI@2
  displayName: 'Publish Pipelines'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: publish
    projects: 'src/Pipelines/LoLPredict.Pipelines'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/Pipelines'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
